# name: upload-pypi
run-name: package and upload to pypi  
on:
  push:
    branches:
      - feat/*
      - fix/*
      - test/*
      - doc/*
      - main
    tags:
      - v1.*
      - v2.*
  pull_request:
    branches: [ master, develop ]
jobs:
  # pypi-publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: alirezatheh/pypi-auto-publish@v1
  #       with:
  #         test-api-pypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         #pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: Build package
        run: python -m build
        # Just adding the test-pypi publish currently.
      # - name: Upload to test-pypi
      #   run: twine upload --repository testpypi dist/*
      #   shell: bash
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/